name: base
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.7.1=py36_0
  - asn1crypto=0.24.0=py36_1003
  - astor=0.7.1=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h14c3975_1001
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hf0e25f4_1
  - chardet=3.0.4=py36_1003
  - conda=4.6.8=py36_0
  - conda-env=2.6.0=1
  - cryptography=2.6.1=py36h72c5cf5_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.3.1=cuda9.0_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py_0
  - glib=2.56.2=hd408876_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h211956c_0
  - idna=2.8=py36_1000
  - intel-openmp=2019.3=199
  - ipython=7.4.0=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.3=py36_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py36h6bb024c_1002
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.7.0=h8b12597_2
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markdown=2.6.11=py_0
  - matplotlib=3.0.3=py36_0
  - matplotlib-base=3.0.3=py36h167e16e_0
  - mkl=2019.3=199
  - mkl_fft=1.0.11=py36h14c3975_0
  - mkl_random=1.0.2=py36h637b7d7_2
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=h6bb024c_0
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py_0
  - openssl=1.1.1b=h14c3975_1
  - pandas=0.24.2=py36hf484d3e_0
  - parso=0.3.4=py_0
  - patchelf=0.9=hf484d3e_1004
  - patsy=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.3=py36_0
  - prompt_toolkit=2.0.9=py_0
  - protobuf=3.7.0=py36he1b5a44_1
  - ptyprocess=0.6.0=py36_1000
  - pycosat=0.6.3=py36h14c3975_1001
  - pycparser=2.19=py36_1
  - pygments=2.3.1=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.3.1=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.6.8=py36_1002
  - python=3.6.7=h381d211_1004
  - python-dateutil=2.8.0=py_0
  - pytorch=1.0.1=cuda90py36h8b0c50b_0
  - pytz=2018.9=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py36_1000
  - ruamel_yaml=0.15.71=py36h14c3975_1000
  - scikit-learn=0.20.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - seaborn=0.9.0=py_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sqlite=3.26.0=h7b6447c_0
  - statsmodels=0.9.0=py36h3010b51_1000
  - tensorboard=1.10.0=py36_0
  - tensorboardx=1.6=py_0
  - tensorflow=1.10.0=py36_0
  - termcolor=1.1.0=py_2
  - tk=8.6.9=h84994c4_1001
  - torchvision=0.2.2=py_3
  - tornado=6.0.2=py36h516909a_0
  - traitlets=4.3.2=py36_1000
  - urllib3=1.24.1=py36_1000
  - wcwidth=0.1.7=py_1
  - werkzeug=0.15.1=py_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/jsenthil/miniconda3

